package equipe03.gerenciador_de_veiculos.igu.menu;

public enum OpcoesBarraDeMenu {
	CADASTRAR_VEICULO,
	CADASTRAR_FUNCIONARIO,
	REGISTRAR_EMPRESTIMO,
	REGISTRAR_DEVOLUCAO,
	SOBRE_PROGRAMA,
	SAIR,
	ABRIR,
	SALVAR,
	SALVAR_COMO;
	

}
